name: gitb
version: "2.0.1"
summary: A command line tool for using Backlog's git comfortably
description: |
  gitb command helps to use Backlog's git comfortably.
  For example, can open PR, issue, branches, tags, etc in the browser with one action.
  Also, gitb wraps all git commands, therefore can execute git-command
  using gitb like a gitb fetch, gitb pull, gitb push, and more...
  Suffix B has multiple meanings. Backlog, Browser, B-Dash.

grade: stable
confinement: classic

apps:
  gitb:
    command: gitb

parts:
  gitb:
    plugin: nil
    build-snaps: [go/1.12/stable]
    source: .
    build-packages:
      - make
      - git
    override-build: |
      snapcraftctl build
      export GOPATH=$(realpath ../go)
      export PATH=$GOPATH/bin:$PATH
      make install
      mv $GOPATH/bin/gitb $SNAPCRAFT_PART_INSTALL